{ AC, CR, JA, WN, AC, LO, AC, JA, AC, AC, AC, AC, JA, KN, AC  }, 	 //1	 0
{ AC, CR, KN, TN, AC, LO, AC, QN, WN, AC, AC, AC, CR, AC, AC  }, 	 //2	 0
{ AC, AC, KN, KN, CR, LO, LO, KN, QN, QN, AC, KN, PF, ST, KN  }, 	 //100	 0
{ AC, CR, PF, TN, QN, LO, AC, QN, AC, KN, AC, AC, QN, AC, AC  }, 	 //4	 0
{ AC, CR, PF, AC, SK, LO, AC, QN, AC, KN, AC, AC, QN, AC, KN  }, 	 //5	 0
{ AC, CR, QN, AC, AC, LO, AC, QN, PF, AC, AC, AC, SK, KN, SK  }, 	 //6	 0
{ AC, CR, KN, KN, AC, LO, AC, KN, SK, AC, AC, AC, KN, QN, AC  }, 	 //7	 0
{ AC, CR, KN, TN, ST, LO, AC, KN, AC, AC, AC, AC, PF, AC, KN  }, 	 //8	 0
{ AC, CR, QN, QN, TN, LO, AC, AC, QN, AC, AC, AC, KN, SK, AC  }, 	 //9	 0
{ KN, ST, KN, AC, KN, KN, JA, KN, PF, KN, SK, TN, KN, KN, CR  }, 	 //1511	 0
{ AC, AC, KN, SK, AC, LO, AC, ST, QN, AC, AC, AC, TN, KN, AC  }, 	 //11	 0
{ AC, AC, ST, AC, QN, LO, AC, TN, AC, QN, AC, AC, TN, AC, SH  }, 	 //12	 0
{ AC, AC, ST, WN, TN, LO, AC, TN, AC, AC, AC, AC, TN, KN, AC  }, 	 //13	 0
{ AC, AC, ST, AC, AC, LO, AC, TN, AC, LO, AC, AC, TN, PF, AC  }, 	 //14	 0
{ AC, AC, TN, CR, JA, LO, AC, TN, AC, JA, AC, AC, TN, AC, WN  }, 	 //15	 0
{ AC, AC, TN, QN, AC, LO, AC, TN, QN, AC, AC, AC, TN, SK, CR  }, 	 //16	 0
{ AC, AC, JA, SH, AC, LO, AC, JA, TN, AC, AC, AC, JA, TN, SK  }, 	 //17	 0
{ AC, AC, JA, CR, AC, LO, AC, JA, AC, AC, AC, AC, CR, AC, AC  }, 	 //18	 0
